### PR TITLE
style(examples/nextjs-trpc): fix code formatting

### PR DESCRIPTION
**Pull request by Mnigos**
I plan to include `react-query` integration, but first I will have to find out how to do it.

### CODE REVIEW

**Comment by KevinEdry** [comment]
You can check how it's done with the Create T3. Just point the client to the nest server.
Also, can you create a new example instead of overriding the existing one?

**Comment by Mnigos** [comment]
> You can check how it's done with the Create T3. Just point the client to the nest server. Also, can you create a new example instead of overriding the existing one?

I wanted to create new example with vite and react-query

**Comment by KevinEdry** [comment]
On second thought, we can just keep the simple frontend example we have here since the client-side isn't any different than any other `trpc` implementation.
We can always link to that their frontend examples if needed.

**Comment by Mnigos** [comment]
> On second thought, we can just keep the simple frontend example we have here since the client-side isn't any different than any other `trpc` implementation. We can always link to that their frontend examples if needed.

Sure, so then I think this pr is ready to merge if you have no contraindications.

**Review by KevinEdry — APPROVED** [review]
Thanks for taking the time fix some of the code formatting issues in the examples.
Approved!

**Pull request merged**
